secret:
  user:
    priv: "-----BEGIN EC PRIVATE KEY-----\nMHcCAQEEIDHtf4B42Yvyt5+ndXLbUBR+9ggcAUNB8tNjmjyGz98uoAoGCCqGSM49\nAwEHoUQDQgAEY6eVUfU9IJT2PavgUp3OWEarqMucEeoH/iTNImDn8z6VSTLPFf+W\nz05ySdN/cUv5jEV6UHLfLj68VZG+RZ7eRw==\n-----END EC PRIVATE KEY-----"
    pub: "-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEY6eVUfU9IJT2PavgUp3OWEarqMuc\nEeoH/iTNImDn8z6VSTLPFf+Wz05ySdN/cUv5jEV6UHLfLj68VZG+RZ7eRw==\n-----END PUBLIC KEY-----"

config:
  domain: 172.25.186.66