// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Password struct {
	UserID     pgtype.Int4
	Password   string
	CreateDate pgtype.Timestamp
	UpdateDate pgtype.Timestamp
}

type Service struct {
	ID          int32
	ServiceName string
	PublicKey   string
	Status      bool
}

type User struct {
	ID              int32
	Username        string
	Name            string
	Email           string
	Dob             string
	Gender          string
	AllowedServices pgtype.Text
	CreateDate      pgtype.Timestamp
	DeleteDate      pgtype.Timestamp
}
