// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPasswordReturnUserId = `-- name: CreatePasswordReturnUserId :one
insert into passwords (
    user_id,
    password,
    create_date
)
values (
    $1,
    $2,
    now()
)
returning user_id
`

type CreatePasswordReturnUserIdParams struct {
	UserID   pgtype.Int4
	Password string
}

func (q *Queries) CreatePasswordReturnUserId(ctx context.Context, arg CreatePasswordReturnUserIdParams) (pgtype.Int4, error) {
	row := q.db.QueryRow(ctx, createPasswordReturnUserId, arg.UserID, arg.Password)
	var user_id pgtype.Int4
	err := row.Scan(&user_id)
	return user_id, err
}

const createUserReturnId = `-- name: CreateUserReturnId :one
insert into users (
    username,
    name,
    email,
    dob,
    gender,
    create_date
)
values (
    $1,
    $2,
    $3,
    $4,
    $5,
    now()
)
returning id
`

type CreateUserReturnIdParams struct {
	Username string
	Name     string
	Email    string
	Dob      string
	Gender   string
}

func (q *Queries) CreateUserReturnId(ctx context.Context, arg CreateUserReturnIdParams) (int32, error) {
	row := q.db.QueryRow(ctx, createUserReturnId,
		arg.Username,
		arg.Name,
		arg.Email,
		arg.Dob,
		arg.Gender,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getUserLatestPassword = `-- name: GetUserLatestPassword :one
select 
    users.id,
    users.username,
    passwords.password
from 
    users
join 
    passwords
on 
    users.id = passwords.user_id
where 
    users.username = $1
and 
    passwords.update_date is null
order by
    passwords.create_date
desc
limit 1
`

type GetUserLatestPasswordRow struct {
	ID       int32
	Username string
	Password string
}

func (q *Queries) GetUserLatestPassword(ctx context.Context, username string) (GetUserLatestPasswordRow, error) {
	row := q.db.QueryRow(ctx, getUserLatestPassword, username)
	var i GetUserLatestPasswordRow
	err := row.Scan(&i.ID, &i.Username, &i.Password)
	return i, err
}
